version: '3.1'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_DB: hackathon
        volumes:
            - "./.db:/var/lib/postgresql/data"
        ports:
            - "5432:5432"
